### ISSUE TITLE
Unable to read .prob files in pred/pro/output/

### ISSUE THREAD

**Issue by meetvora** [zhengshou/scnn#10]
Hi,

When I execute ```ipython -i -- run_demo.py -i video/video_test_0000131.mp4 -f 25```
I received the following error:
```python
extract frames starts
extract frames done in 2.8206 s
init sliding window starts
init sliding window done in 0.0045 s
generate proposal list starts
generate proposal list done in 0.0028 s
run proposal network starts
run proposal network done in 0.5959 s
read proposal results starts

/home/ubuntu/meet/scnn/demo/run_demo.py in main()
     93     # read proposal results
     94     for img_index in range(len(seg_swin)):
---> 95         prob = read_binary_blob(preddir+'pro/output/'+'{0:06}'.format(img_index+1)+'.prob')
     96         seg_swin[img_index][9] = prob[1]
     97 

/home/ubuntu/meet/scnn/demo/run_demo.py in read_binary_blob(filename)
    238 
    239 def read_binary_blob(filename):
--> 240     f = open(filename, 'rb')
    241     s = struct.unpack('iiiii', f.read(20)) # the first five are integers
    242     length = s[0]*s[1]*s[2]*s[3]*s[4]

IOError: [Errno 2] No such file or directory: 'pred/pro/output/000001.prob'
```

On further inspection, it seems that C3D isn't writing .prob files in feature_extract.sh

Thank you for help in advance :)

**Comment by leileestone** [comment]
@hello I also met such problem, Did you fix it?

**Comment by 503004220** [comment]
> Hi,
> 
> When I execute `ipython -i -- run_demo.py -i video/video_test_0000131.mp4 -f 25`
> I received the following error:
> 
> ```python
> extract frames starts
> extract frames done in 2.8206 s
> init sliding window starts
> init sliding window done in 0.0045 s
> generate proposal list starts
> generate proposal list done in 0.0028 s
> run proposal network starts
> run proposal network done in 0.5959 s
> read proposal results starts
> 
> /home/ubuntu/meet/scnn/demo/run_demo.py in main()
>      93     # read proposal results
>      94     for img_index in range(len(seg_swin)):
> ---> 95         prob = read_binary_blob(preddir+'pro/output/'+'{0:06}'.format(img_index+1)+'.prob')
>      96         seg_swin[img_index][9] = prob[1]
>      97 
> 
> /home/ubuntu/meet/scnn/demo/run_demo.py in read_binary_blob(filename)
>     238 
>     239 def read_binary_blob(filename):
> --> 240     f = open(filename, 'rb')
>     241     s = struct.unpack('iiiii', f.read(20)) # the first five are integers
>     242     length = s[0]*s[1]*s[2]*s[3]*s[4]
> 
> IOError: [Errno 2] No such file or directory: 'pred/pro/output/000001.prob'
> ```
> 
> On further inspection, it seems that C3D isn't writing .prob files in feature_extract.sh
> 
> Thank you for help in advance :)

hello，may i ask how to solve this problem

**Comment by 503004220** [comment]
> Hi! I'm having the same problem. Does anyone have solved it? Thanks!

hello，may i ask how to solve this problem
