### ISSUE TITLE
question_score

### ISSUE THREAD

**Issue by Kerry0123** [zhengshou/scnn#11]
finetuning my datasets:
I0605 15:54:41.693938 12509 solver.cpp:142] Test score #0: 0.146302
I0605 15:54:41.693992 12509 solver.cpp:142] Test score #1: 15.5048
I0605 15:54:41.694018 12509 net.cpp:355] Serializing 30 layers
I0605 15:54:42.801959 12509 solver.cpp:159] Snapshotting to snapshot/SCNN_uniform16_cls20_iter_30000
I0605 15:54:47.106016 12509 solver.cpp:166] Snapshotting solver state to snapshot/SCNN_uniform16_cls20_iter_30000.solverstate
I0605 15:54:49.264902 12509 net.cpp:355] Serializing 30 layers
I0605 15:54:50.062696 12509 solver.cpp:159] Snapshotting to snapshot/SCNN_uniform16_cls20_iter_30000
I0605 15:54:55.804988 12509 solver.cpp:166] Snapshotting solver state to snapshot/SCNN_uniform16_cls20_iter_30000.solverstate
I0605 15:55:00.132752 12509 solver.cpp:100] Optimization Done.
I0605 15:55:00.132803 12509 finetune_net.cpp:30] Optimization Done.

 Test score #0: 0.146302 is accuracy?
Test score #1: 15.5048
Is my result correct?

**Comment by zhengshou** [comment]
Yes test score #0 is accuracy.
