### ISSUE TITLE
compile C3D-v1.1/C3D_sample_rate

### ISSUE THREAD

**Issue by buaa-luzhi** [zhengshou/scnn#13]
CXX/LD -o .build_release/examples/siamese/convert_mnist_siamese_data.bin
.build_release/lib/libcaffe.so: undefined reference to `cv::VideoCapture::set(int, double)'
.build_release/lib/libcaffe.so: undefined reference to `cv::VideoCapture::open(cv::String const&)'
.build_release/lib/libcaffe.so: undefined reference to `cv::VideoCapture::release()'
.build_release/lib/libcaffe.so: undefined reference to `cv::VideoCapture::~VideoCapture()'
.build_release/lib/libcaffe.so: undefined reference to `cv::VideoCapture::isOpened() const'
.build_release/lib/libcaffe.so: undefined reference to `cv::VideoCapture::get(int) const'
.build_release/lib/libcaffe.so: undefined reference to `cv::VideoCapture::read(cv::_OutputArray const&)'
.build_release/lib/libcaffe.so: undefined reference to `cv::VideoCapture::VideoCapture()'
collect2: error: ld returned 1 exit status
make: *** [.build_release/tools/extract_image_features.bin] Error 1
make: *** Waiting for unfinished jobs....
.build_release/lib/libcaffe.so: undefined reference to `cv::VideoCapture::set(int, double)'
.build_release/lib/libcaffe.so: undefined reference to `cv::VideoCapture::open(cv::String const&)'
.build_release/lib/libcaffe.so: undefined reference to `cv::VideoCapture::release()'
.build_release/lib/libcaffe.so: undefined reference to `cv::VideoCapture::~VideoCapture()'
.build_release/lib/libcaffe.so: undefined reference to `cv::VideoCapture::isOpened() const'
.build_release/lib/libcaffe.so: undefined reference to `cv::VideoCapture::get(int) const'
.build_release/lib/libcaffe.so: undefined reference to `cv::VideoCapture::read(cv::_OutputArray const&)'
.build_release/lib/libcaffe.so: undefined reference to `cv::VideoCapture::VideoCapture()'
collect2: error: ld returned 1 exit status
make: *** [.build_release/tools/upgrade_solver_proto_text.bin] Error 1
.build_release/lib/libcaffe.so: undefined reference to `cv::VideoCapture::set(int, double)'
.build_release/lib/libcaffe.so: undefined reference to `cv::VideoCapture::open(cv::String const&)'
.build_release/lib/libcaffe.so: undefined reference to `cv::VideoCapture::release()'
.build_release/lib/libcaffe.so: undefined reference to `cv::VideoCapture::~VideoCapture()'
.build_release/lib/libcaffe.so: undefined reference to `cv::VideoCapture::isOpened() const'
.build_release/lib/libcaffe.so: undefined reference to `cv::VideoCapture::get(int) const'
.build_release/lib/libcaffe.so: undefined reference to `cv::VideoCapture::read(cv::_OutputArray const&)'
.build_release/lib/libcaffe.so: undefined reference to `cv::VideoCapture::VideoCapture()'
collect2: error: ld returned 1 exit status
make: *** [.build_release/tools/compute_image_mean.bin] Error 1
.build_release/lib/libcaffe.so: undefined reference to `cv::VideoCapture::set(int, double)'
.build_release/lib/libcaffe.so: undefined reference to `cv::VideoCapture::open(cv::String const&)'
.build_release/lib/libcaffe.so: undefined reference to `cv::VideoCapture::release()'
.build_release/lib/libcaffe.so: undefined reference to `cv::VideoCapture::~VideoCapture()'
.build_release/lib/libcaffe.so: undefined reference to `cv::VideoCapture::isOpened() const'
.build_release/lib/libcaffe.so: undefined reference to `cv::VideoCapture::get(int) const'
.build_release/lib/libcaffe.so: undefined reference to `cv::VideoCapture::read(cv::_OutputArray const&)'
.build_release/lib/libcaffe.so: undefined reference to `cv::VideoCapture::VideoCapture()'
collect2: error: ld returned 1 exit status
make: *** [.build_release/tools/caffe.bin] Error 1
.build_release/lib/libcaffe.so: undefined reference to `cv::VideoCapture::set(int, double)'
.build_release/lib/libcaffe.so: undefined reference to `cv::VideoCapture::open(cv::String const&)'
.build_release/lib/libcaffe.so: undefined reference to `cv::VideoCapture::release()'
.build_release/lib/libcaffe.so: undefined reference to `cv::VideoCapture::~VideoCapture()'
.build_release/lib/libcaffe.so: undefined reference to `cv::VideoCapture::isOpened() const'
.build_release/lib/libcaffe.so: undefined reference to `cv::VideoCapture::get(int) const'
.build_release/lib/libcaffe.so: undefined reference to `cv::VideoCapture::read(cv::_OutputArray const&)'
.build_release/lib/libcaffe.so: undefined reference to `cv::VideoCapture::VideoCapture()'
collect2: error: ld returned 1 exit status
make: *** [.build_release/tools/upgrade_net_proto_binary.bin] Error 1
.build_release/lib/libcaffe.so: undefined reference to `cv::VideoCapture::set(int, double)'
.build_release/lib/libcaffe.so: undefined reference to `cv::VideoCapture::open(cv::String const&)'
.build_release/lib/libcaffe.so: undefined reference to `cv::VideoCapture::release()'
.build_release/lib/libcaffe.so: undefined reference to `cv::VideoCapture::~VideoCapture()'
.build_release/lib/libcaffe.so: undefined reference to `cv::VideoCapture::isOpened() const'
.build_release/lib/libcaffe.so: undefined reference to `cv::VideoCapture::get(int) const'
.build_release/lib/libcaffe.so: undefined reference to `cv::VideoCapture::read(cv::_OutputArray const&)'
.build_release/lib/libcaffe.so: undefined reference to `cv::VideoCapture::VideoCapture()'
collect2: error: ld returned 1 exit status
make: *** [.build_release/tools/extract_features.bin] Error 1
.build_release/lib/libcaffe.so: undefined reference to `cv::VideoCapture::set(int, double)'
.build_release/lib/libcaffe.so: undefined reference to `cv::VideoCapture::open(cv::String const&)'
.build_release/lib/libcaffe.so: undefined reference to `cv::VideoCapture::release()'
.build_release/lib/libcaffe.so: undefined reference to `cv::VideoCapture::~VideoCapture()'
.build_release/lib/libcaffe.so: undefined reference to `cv::VideoCapture::isOpened() const'
.build_release/lib/libcaffe.so: undefined reference to `cv::VideoCapture::get(int) const'
.build_release/lib/libcaffe.so: undefined reference to `cv::VideoCapture::read(cv::_OutputArray const&)'
.build_release/lib/libcaffe.so: undefined reference to `cv::VideoCapture::VideoCapture()'
collect2: error: ld returned 1 exit status
make: *** [.build_release/examples/cifar10/convert_cifar_data.bin] Error 1
.build_release/lib/libcaffe.so: undefined reference to `cv::VideoCapture::set(int, double)'
.build_release/lib/libcaffe.so: undefined reference to `cv::VideoCapture::open(cv::String const&)'
.build_release/lib/libcaffe.so: undefined reference to `cv::VideoCapture::release()'
.build_release/lib/libcaffe.so: undefined reference to `cv::VideoCapture::~VideoCapture()'
.build_release/lib/libcaffe.so: undefined reference to `cv::VideoCapture::isOpened() const'
.build_release/lib/libcaffe.so: undefined reference to `cv::VideoCapture::get(int) const'
.build_release/lib/libcaffe.so: undefined reference to `cv::VideoCapture::read(cv::_OutputArray const&)'
.build_release/lib/libcaffe.so: undefined reference to `cv::VideoCapture::VideoCapture()'
collect2: error: ld returned 1 exit status
make: .*** [.build_release/tools/upgrade_net_proto_text.bin] Error 1build_release
/lib/libcaffe.so: undefined reference to `cv::VideoCapture::set(int, double)'
.build_release/lib/libcaffe.so: undefined reference to `cv::VideoCapture::open(cv::String const&)'
.build_release/lib/libcaffe.so: undefined reference to `cv::VideoCapture::release()'
.build_release/lib/libcaffe.so: undefined reference to `cv::VideoCapture::~VideoCapture()'
.build_release/lib/libcaffe.so: undefined reference to `cv::VideoCapture::isOpened() const'
.build_release/lib/libcaffe.so: undefined reference to `cv::VideoCapture::get(int) const'
.build_release/lib/libcaffe.so: undefined reference to `cv::VideoCapture::read(cv::_OutputArray const&)'
.build_release/lib/libcaffe.so: undefined reference to `cv::VideoCapture::VideoCapture()'
collect2: error: ld returned 1 exit status
make: *** [.build_release/tools/convert_imageset.bin] Error 1
.build_release/lib/libcaffe.so: undefined reference to `cv::VideoCapture::set(int, double)'
.build_release/lib/libcaffe.so: undefined reference to `cv::VideoCapture::open(cv::String const&)'
.build_release/lib/libcaffe.so: undefined reference to `cv::VideoCapture::release()'
.build_release/lib/libcaffe.so: undefined reference to `cv::VideoCapture::~VideoCapture()'
.build_release/lib/libcaffe.so: undefined reference to `cv::VideoCapture::isOpened() const'
.build_release/lib/libcaffe.so: undefined reference to `cv::VideoCapture::get(int) const'
.build_release/lib/libcaffe.so: undefined reference to `cv::VideoCapture::read(cv::_OutputArray const&)'
.build_release/lib/libcaffe.so: undefined reference to `cv::VideoCapture::VideoCapture()'
collect2: error: ld returned 1 exit status
make: *** [.build_release/examples/cpp_classification/classification.bin] Error 1
.build_release/lib/libcaffe.so: undefined reference to `cv::VideoCapture::set(int, double)'
.build_release/lib/libcaffe.so: undefined reference to `cv::VideoCapture::open(cv::String const&)'
.build_release/lib/libcaffe.so: undefined reference to `cv::VideoCapture::release()'
.build_release/lib/libcaffe.so: undefined reference to `cv::VideoCapture::~VideoCapture()'
.build_release/lib/libcaffe.so: undefined reference to `cv::VideoCapture::isOpened() const'
.build_release/lib/libcaffe.so: undefined reference to `cv::VideoCapture::get(int) const'
.build_release/lib/libcaffe.so: undefined reference to `cv::VideoCapture::read(cv::_OutputArray const&)'
.build_release/lib/libcaffe.so: undefined reference to `cv::VideoCapture::VideoCapture()'
collect2: error: ld returned 1 exit status
make: *** [.build_release/examples/siamese/convert_mnist_siamese_data.bin] Error 1
.build_release/lib/libcaffe.so: undefined reference to `cv::VideoCapture::set(int, double)'
.build_release/lib/libcaffe.so: undefined reference to `cv::VideoCapture::open(cv::String const&)'
.build_release/lib/libcaffe.so: undefined reference to `cv::VideoCapture::release()'
.build_release/lib/libcaffe.so: undefined reference to `cv::VideoCapture::~VideoCapture()'
.build_release/lib/libcaffe.so: undefined reference to `cv::VideoCapture::isOpened() const'
.build_release/lib/libcaffe.so: undefined reference to `cv::VideoCapture::get(int) const'
.build_release/lib/libcaffe.so: undefined reference to `cv::VideoCapture::read(cv::_OutputArray const&)'
.build_release/lib/libcaffe.so: undefined reference to `cv::VideoCapture::VideoCapture()'
collect2: error: ld returned 1 exit status
make: *** [.build_release/examples/mnist/convert_mnist_data.bin] Error 1

**Comment by buaa-luzhi** [comment]
when I compile C3D_sample_rate, always having problems. The version of opencv 3.2.0. Who can tell me how to solve this problem? 
Thank you very much!

**Comment by zhengshou** [comment]
Our code is based on C3D. You may want to look into C3D github repo to learn its usage. Thanks.
