### ISSUE TITLE
Input data file list

### ISSUE THREAD

**Issue by carloscaetano** [zhengshou/scnn#14]
Hi @zhengshou , thanks for your sharing.

Could you please provide the input data files list you used to train and test the Proposal network? I saw that you shared some sample files, but I would appreciate a lot if you could provide me the original files you used... with all the rows. It would help me a lot. My interest is just for academic purposes.

Thanks in advance.

**Comment by zhengshou** [comment]
Hi,

Thank you for your interest. Unfortunately since I did this project two years ago, I do not keep a copy of original files now.

Best,
Zheng
