### ISSUE TITLE
Semantic of files in experiments/THUMOS14/annotation and eval/tmp.txt

### ISSUE THREAD

**Issue by minhtriet** [zhengshou/scnn#21]
The first line of BaseballPitch_test.txt reads:
`video_test_0000324  49.2 53.5`
What is the meaning of the two later numbers? I assume that this is a begin and end second?
Also, the first line in eval/tmp.txt reads
`video_test_0000188 518.4 523.5 13 0.48942`, which is not very obvious
Thank you and best regards,

**Comment by zhengshou** [comment]
yes begin and end second
