### ISSUE TITLE
frame_extraction.log shows that ffmepg is not found?

### ISSUE THREAD

**Issue by leileestone** [zhengshou/scnn#23]
sh: 1: ../lib/preprocess/ffmpeg: not found
I have downloaded the ffmepg into this path /lib/postprocess

**Comment by leileestone** [comment]
sh: 1: ../lib/preprocess/ffmpeg: Permission denied
how to fix this???

**Comment by 503004220** [comment]
> sh: 1: ../lib/preprocess/ffmpeg: Permission denied
> how to fix this???

May i ask how to fix this problem?
