### ISSUE TITLE
demo problem

### ISSUE THREAD

**Issue by leileestone** [zhengshou/scnn#24]
When I run the demo, there is a error that show [Errno 2] No such file or directory: 'pred/pro/output/000001.prob'
so I cheak the log of demo_extract.log. there is another problem.
[libprotobuf ERROR google/protobuf/text_format.cc:274] Error parsing text-format caffe.NetParameter: 5:3: Unknown enumeration value of "VIDEO_DATA" for field "type".
and I found the demo is based on C3D-V1.0, and the demo_finetuning_feature_extract.prototxt file is different with C3D-V1.1. can you tell me how to fix this problem.

**Comment by 503004220** [comment]
> Hi @leileestone I'm running into the same problem. Did you manage to fix it?

hi jin-zhe, did you handle this problem?
many thanks
