### ISSUE TITLE
experiment/THUMOS14/network_proposal/result/res_seg_swin.mat

### ISSUE THREAD

**Issue by wangwen39** [zhengshou/scnn#25]
Thanks for your reading!
How can I produce the res_seg_swin.mat file? what does the file used for?
Looking forward to your replay! sincerely

**Comment by Multihuntr** [comment]
Actually, there does seem to be some code that creates a seg_swin.mat: https://github.com/zhengshou/scnn/blob/master/demo/run_demo.m

There is no information on seg_swin(:,[7 8 13 14]), so I guess we can ignore them?

And to answer the question: "what does the file used for?", you can use it to run the evaluation script linked in my previous message to get the final mAP.

**Comment by zhengshou** [comment]
Hi,

Sorry for the late reply.

We have already explained in the readme file what does each column in this mat file mean.

Yes, you can ignore [7 8 13 14].
