### ISSUE TITLE
Changes to VideoDataLayer break test cases for C3D

### ISSUE THREAD

**Issue by Multihuntr** [zhengshou/scnn#27]
This repository just instructs users to follow the C3D installation instructions, and as part of those instructions it tells users to run `make runtest` to ensure it has been installed correctly. The edits made to the C3D implementations break the test cases and since there was no mention of this in this repository it is very misleading. i.e. it suggests that C3D has not been installed correctly.

Can you either fix the test cases or put a note into the README.md in this repo's root mentioning that the test cases for VideoDataLayer are expected to fail?

**Comment by zhengshou** [comment]
Thanks much for the heads-up. Will update readme file.
