### ISSUE TITLE
The question about eval result 

### ISSUE THREAD

**Issue by Yanchunswallow** [zhengshou/scnn#29]
Hi Zheng:
    I have read your work carefully.
    I attempt to evaluate the test result to 210 test videos base on your demo code, but the result is different to yours:
---------------------------------------
     |  0.1  | 0.2   |  0.3  |  0.4  |  0.5 |
     |47.7  | 43.5 | 36.3 | 28.7 | 19.0|
---------------------------------------
my test results used your evaluation code.
---------------------------------------
     |  0.1  | 0.2   |  0.3  |  0.4  |  0.5 |
     | 26.3 | 26.7 | 24.6 | 22.9 | 18.9|
---------------------------------------
I don't know why there is such a big different?  
Thanks in advance!

**Comment by zhengshou** [comment]
Thank you for your interest in our work. Some people have reproduced the results. Maybe you can check your data preparation or S-CNN usage in detail.

**Comment by Yanchunswallow** [comment]
@zhengshou Thank you for your reply! 
BTW, could you please release or send me the trained model of MEXaction2 dataset? My email is 2570646589@qq.com. Thanks very much!
