### ISSUE TITLE
The problem of the run_demo.m and the demo_list_test_uniform16_proposal.lst

### ISSUE THREAD

**Issue by timbryant** [zhengshou/scnn#30]
Hi,zhengshou
Thank you for your hard work and I am very interested in your work.
When I run the run_demo.m,I have some question, so I hope you can give me some suggestions.
 I run the code, which is released and I didn't modify any code.
When I run the code as below:
system('./pred/pro/feature_extract.sh');
there was an error said /pred/pro/feature_extract.sh: Aborted
and the log said 
 I0315 15:31:35.568035 22271 video_data_layer.cpp:318] A total of 1589 video chunks.
I0315 15:31:35.568049 22271 video_data_layer.cpp:345] read video from frame/video_test_0000131/
F0315 15:31:35.568114 22271 video_data_layer.cpp:347] Check failed: ReadImageSequenceToVolumeDatum(file_list_[id].c_str(), 1, label_list_[id], new_length, new_height, new_width, sampling_rate, &datum) , and I guess the reason may be the length of the clips,
and I check the demo_list_test_uniform16_proposal.lst, which is generated by the code and from the test-video. As I used the C3D and I know the each row of the lst is a clip of 16 frames.
But in demo_list_test_uniform16_proposal.lst,for example 
frame/video_test_0000131/ 1 0 1
frame/video_test_0000131/ 5 0 1
the 1 is the start frame and the last 1 is the stepsize,which means the next frame index = 1+1, the length of the clips maybe 4,and the start frame of the next clip is 5.
I wander how to sovle the error,and how to ensure the length of clips.
Best 
Tim

**Comment by zhengshou** [comment]
Thanks for your interest in our work.

frame/video_test_0000131/ 1 0 1
frame/video_test_0000131/ 5 0 1

In this case, actually the first clip read by C3D is from 1 to 16 and the second clip to be read is 5-20.

**Comment by timbryant** [comment]
Hi,zhengshou
Thank you for your replying.I'm so sorry to trouble you again. I'm very interested in your work. So I have some questiones of how to prepare the training lst of the proposal networks and the details of the training procedures.
I write the code to generate the lst,  but I think there maybe some misunderstanding.
Fisrst of all, in my code, for the all videos (trimmed videos and untrimmed videos), I have conduct the sliding windows,and set the label of every segments of the trimmed videos to 1(positive label), and set the instance of the untrimmed videos to 1(positive label),and the background to 0(negative label). Am I right?
If I am right, there are a lot of rows, at least 100k rows in the lst. But as mentioned in your paper, all three stages, the training itrations are 30k. So I think my code to generate the training lst is wrong.
So, my questiones as follows
1 how to use the trimmed videos, do I need to use the sliding windows to the trimmed windows? If not , how to generate the trianing lst of the trimmed videos?
2 For the untrimmed videoes, as the videos are more longer than the trimmed videos, and there will be a lot of segments for each videos, do I need to use them all? here is my lst sample
BaseballPitch/video_validation_0000266/ 3329 0 32
BaseballPitch/video_validation_0000266/ 3457 0 32
BaseballPitch/video_validation_0000266/ 3585 0 32
BaseballPitch/video_validation_0000266/ 3713 0 32
BaseballPitch/video_validation_0000681/ 1 0 1
BaseballPitch/video_validation_0000681/ 5 0 1
BaseballPitch/video_validation_0000681/ 9 0 1
BaseballPitch/video_validation_0000681/ 13 0 1
BaseballPitch/video_validation_0000681/ 17 0 1
BaseballPitch/video_validation_0000681/ 21 0 1
BaseballPitch/video_validation_0000681/ 25 0 1
please help me to check out is there some mistakes in my lst.
hope your reply,thanks
best wishes
Tim

**Comment by timbryant** [comment]
我:
我先写封英文邮件
我:
Hi,zhengshou
Thank you for your replying.I'm so sorry to trouble you again. I'm very interested in your work. So I have some questiones of how to prepare the training lst of the proposal networks and the details of the training procedures.
I write the code to generate the lst,  but I think there maybe some misunderstanding.
Fisrst of all, in my code, for the all videos (trimmed videos and untrimmed videos), I have conduct the sliding windows,and set the label of every segments of the trimmed videos to 1(positive label), and set the instance of the untrimmed videos to 1(positive label),and the background to 0(negative label). Am I right?
If I am right, there are a lot of rows, at least 100k rows in the lst. But as mentioned in your paper, all three stages, the training itrations are 30k. So I think my code to generate the training lst is wrong.
So, my questiones as follows
1 how to use the trimmed videos, do I need to use the sliding windows to the trimmed windows? If not , how to generate the trianing lst of the trimmed videos?
2 For the untrimmed videoes, as the videos are more longer than the trimmed videos, and there will be a lot of segments for each videos, do I need to use them all? here is my lst sample
BaseballPitch/v_BaseballPitch_g25_c07/ 73 1 2
BaseballPitch/v_BaseballPitch_g25_c07/ 81 1 2
BaseballPitch/v_BaseballPitch_g25_c07/ 1 1 4
BaseballPitch/v_BaseballPitch_g25_c07/ 17 1 4
BaseballPitch/v_BaseballPitch_g25_c07/ 33 1 4
BaseballPitch/v_BaseballPitch_g25_c07/ 49 1 4
BaseballPitch/video_validation_0000266/ 1 0 1
BaseballPitch/video_validation_0000266/ 5 0 1
BaseballPitch/video_validation_0000266/ 9 0 1
BaseballPitch/video_validation_0000266/ 13 0 1
BaseballPitch/video_validation_0000266/ 17 0 1
BaseballPitch/video_validation_0000266/ 21 0 1
BaseballPitch/video_validation_0000266/ 25 0 1
BaseballPitch/video_validation_0000266/ 29 0 1
BaseballPitch/video_validation_0000266/ 33 0 1
BaseballPitch/video_validation_0000266/ 37 0 1
please help me to check out is there some mistakes in my lst.
hope your reply,thanks
best wishes
Tim

**Comment by timbryant** [comment]
Hi,zhengshou
Thank you for your replying.I'm so sorry to trouble you again. I'm very interested in your work. So I have some questiones of how to prepare the training lst of the proposal networks and the details of the training procedures.
I write the code to generate the lst, but I think there maybe some misunderstanding.
Fisrst of all, in my code, for the all videos (trimmed videos and untrimmed videos), I have conduct the sliding windows,and set the label of every segments of the trimmed videos to 1(positive label), and set the instance of the untrimmed videos to 1(positive label),and the background to 0(negative label). Am I right?
If I am right, there are a lot of rows, at least 100k rows in the lst. But as mentioned in your paper, all three stages, the training itrations are 30k. So I think my code to generate the training lst is wrong.
So, my questiones as follows
1 how to use the trimmed videos, do I need to use the sliding windows to the trimmed windows? If not , how to generate the trianing lst of the trimmed videos?
2 For the untrimmed videoes, as the videos are more longer than the trimmed videos, and there will be a lot of segments for each videos, do I need to use them all? here is my lst sample
BaseballPitch/v_BaseballPitch_g25_c07/ 73 1 2
BaseballPitch/v_BaseballPitch_g25_c07/ 81 1 2
BaseballPitch/v_BaseballPitch_g25_c07/ 1 1 4
BaseballPitch/v_BaseballPitch_g25_c07/ 17 1 4
BaseballPitch/v_BaseballPitch_g25_c07/ 33 1 4
BaseballPitch/v_BaseballPitch_g25_c07/ 49 1 4
BaseballPitch/video_validation_0000266/ 1 0 1
BaseballPitch/video_validation_0000266/ 5 0 1
BaseballPitch/video_validation_0000266/ 9 0 1
BaseballPitch/video_validation_0000266/ 13 0 1
BaseballPitch/video_validation_0000266/ 17 0 1
BaseballPitch/video_validation_0000266/ 21 0 1
BaseballPitch/video_validation_0000266/ 25 0 1
BaseballPitch/video_validation_0000266/ 29 0 1
BaseballPitch/video_validation_0000266/ 33 0 1
BaseballPitch/video_validation_0000266/ 37 0 1
please help me to check out is there some mistakes in my lst.
hope your reply,thanks
best wishes
Tim
