### ISSUE TITLE
question about run "run_demo.m"

### ISSUE THREAD

**Issue by sophiazy** [zhengshou/scnn#5]
when I run the "run_demo.m" ,the following question is:

init sliding window startsinit sliding window done in 2.4115 s
generate proposal startsgenerate proposal list done in 1.06 s
run proposal network starts
run proposal network done in 0.11494 s
read proposal results startsread proposal results done in 0.21835 s
generate localization list starts
generate localization list done in 0.000827 s
run localization results starts
run localization results done in 0.011421 s
read localization results starts
Improper assignment with rectangular empty matrix.

Error in run_demo (line 165)
seg_swin(:,9) = a;

Tried many ways, but still no solution.I would appreciated for some advice,very thanks!

**Comment by zhengshou** [comment]
seems not results returned from C3D. could you also post your log files from C3D/Caffe?

**Comment by sophiazy** [comment]
The log file content is:
/scnn-master/demo$ cat demo_extract.log 
./pred/loc/feature_extract.sh: line 1: ../../../C3D_overlap_loss/build/tools/extract_image_features.bin: No such file or directory

**Comment by zhengshou** [comment]
you should check your directory during execution. did you change to demo directory: cd ./demo/. before running the demo? could you print out your execution path in the mat file right before exec ./pred/loc/feature_extract.sh ?

**Comment by sophiazy** [comment]
I find a strange problem,as long as I run the "run_demo.m",th file content in the "/demo/pre/loc/demo_list_test_prefix_localization.lst " and "/demo/pre/locdemo_list_test_uniform16_localization.lst" will be empty,but the file exist.so I think the above problem is relevant this problem

**Comment by zhengshou** [comment]
are demo_list_test_prefix_proposal.lst and demo_list_test_uniform16_proposal.lst also empty? otherwise localization list is empty is due to your proposal network returns nothing.

**Comment by sophiazy** [comment]
I may not be state the question clear.
"demo_list_test_prefix_localization.lst"  "demo_list_test_uniform16_localization.lst" original is not empty in the source code .
as long as I run the "run_demo.m",th file content in the "/demo/pre/loc/demo_list_test_prefix_localization.lst " and "/demo/pre/loc/demo_list_test_uniform16_localization.lst" will be empty,but the file exist.so I think the above problem is relevant this problem

**Comment by zhengshou** [comment]
as I mentioned in the above, the localization list is empty is exactly due to the proposal network returns nothing - basically no segment is predicted to likely contain action.

So I was wondering whether demo_list_test_prefix_proposal.lst and demo_list_test_uniform16_proposal.lst are also empty and whether you can run the proposal network successfully.

**Comment by sophiazy** [comment]
demo_list_test_prefix_proposal.lst and demo_list_test_uniform16_proposal.lst are not empty and generate "/pred/pro/seg_swin.mat" file.so I think I run the proposal network successfully.

**Comment by zhengshou** [comment]
are you testing with the demo video or your own video - probably the model cannot detect any actions in your provided video...

**Comment by sophiazy** [comment]
sorrt to be a bothered ,I have another question about the run_demo.m, I don't understand the code in line(122-126):
%.........................................................................................................................................
img = dir( [preddir 'loc/output/'] ); % be careful whether all are jpg
for img_index = 3:size(img,1)
    [~,prob(img_index-2,:)] = read_binary_blob([preddir 'pro/output/' img(img_index).name]);
end
seg_swin(:,10) = prob(:,2);
%...........................................................................................................................................
in addition,the  content "pred/pro/output/" is also empty.

**Comment by zhengshou** [comment]
so prob is also empty? prob is the confidence score of being action for each segment.

**Comment by sophiazy** [comment]
prob are all zeros

**Comment by sophiazy** [comment]
I read the run_demo.m carefully ,there is no file generate in the /pred/pro/output,so the prob is empty,I  don't understand the role of the "/pred/pro/output",I would appreciate for your answer.

**Comment by zhengshou** [comment]
"/pred/pro/output" is used to store all features extracted by C3D (here confidence score fc8 values). so this indicates your proposal network (at least the feature extraction part) is not running correctly. I would suggest you, just in case that you are not, to get familiar with feature extraction using original C3D.

**Comment by sophiazy** [comment]
@zhengshou 
Thanks. I run a shell in original C3D.and I extract the feature in the output file.
namely,"/original C3D root path/example/c3d_feature_extraction/c3d_sport1m_feature_extraction_frm.sh",
the shell content is below:
...........................................................................................................................................
GLOG_logtosterr=1 ../../build/tools/extract_image_features.bin prototxt/c3d_sport1m_feature_extractor_frm.prototxt conv3d_deepnetA_sport1m_iter_1900000 0 50 1 prototxt/output_list_prefix.txt fc7-1 fc6-1 prob
.............................................................................................................................................
However,in the "/scnn-master/demo/pred/pro/feature_extract.sh",the shell content is below:
.............................................................................................................................................
GLOG_logtosterr=1 ../../../C3D_sample_rate/build/tools/extract_image_features.bin demo_finetuning_feature_extract.prototxt ../../../models/THUMOS14/proposal/snapshot/SCNN_uniform16_binary_iter_30000 0 10 100000 demo_list_test_prefix_proposal.lst prob

I think there is no problem in the shell.so I think the problem may come out in the C3D_sample_rate,when I run the "make runtest" the problem is below:


[----------] 2 tests from HingeLossLayerTest/1, where TypeParam = double
[ RUN      ] HingeLossLayerTest/1.TestGradientCPU
[       OK ] HingeLossLayerTest/1.TestGradientCPU (31 ms)
[ RUN      ] HingeLossLayerTest/1.TestGradientGPU
[       OK ] HingeLossLayerTest/1.TestGradientGPU (32 ms)
[----------] 2 tests from HingeLossLayerTest/1 (63 ms total)

[----------] 10 tests from BenchmarkTest
[ RUN      ] BenchmarkTest.TestTimerConstructorCPU
[       OK ] BenchmarkTest.TestTimerConstructorCPU (0 ms)
[ RUN      ] BenchmarkTest.TestTimerStartCPU
[       OK ] BenchmarkTest.TestTimerStartCPU (0 ms)
[ RUN      ] BenchmarkTest.TestTimerMilliSecondsCPU
[       OK ] BenchmarkTest.TestTimerMilliSecondsCPU (300 ms)
[ RUN      ] BenchmarkTest.TestTimerConstructorGPU
[       OK ] BenchmarkTest.TestTimerConstructorGPU (0 ms)
[ RUN      ] BenchmarkTest.TestTimerSecondsGPU
[       OK ] BenchmarkTest.TestTimerSecondsGPU (301 ms)
[ RUN      ] BenchmarkTest.TestTimerMilliSecondsGPU
F0308 09:32:15.140877  8460 test_benchmark.cpp:130] Check failed: timer.MilliSeconds() >= 298 (296.281 vs. 298) 
*** Check failure stack trace: ***
    @     0x2ac14332bdbd  google::LogMessage::Fail()
    @     0x2ac14332dc5d  google::LogMessage::SendToLog()
    @     0x2ac14332b9ac  google::LogMessage::Flush()
    @     0x2ac14332e57e  google::LogMessageFatal::~LogMessageFatal()
    @           0x4f1212  caffe::BenchmarkTest_TestTimerMilliSecondsGPU_Test::TestBody()
    @           0x54370a  testing::internal::HandleExceptionsInMethodIfSupported<>()
    @           0x5389a9  testing::Test::Run()
    @           0x538a87  testing::TestInfo::Run()
    @           0x538bc5  testing::TestCase::Run()
    @           0x538e3d  testing::internal::UnitTestImpl::RunAllTests()
    @           0x54328a  testing::internal::HandleExceptionsInMethodIfSupported<>()
    @           0x538201  testing::UnitTest::Run()
    @           0x41343d  main
    @     0x2ac14588af45  (unknown)
    @           0x418b9e  (unknown)
make: *** [runtest] Aborted (core dumped)

**Comment by zhengshou** [comment]
as I mentioned in previous emails with you, we did not modify test units and thus running test units will not pass for sure. as for your question about how to generate list files, please refer to samples in scnn/experiments/THUMOS14/

**Comment by sophiazy** [comment]
Dear Mr shou:
When I run the "run_demo.m",I find the "./pred/prp/feature_extract.sh" is not run successfully. in the demo_extract.log,the content is:
...............................................................................................................................
WARNING: Logging before InitGoogleLogging() is written to STDERR
E0320 09:39:50.723762 40383 extract_image_features.cpp:55] Using GPU #0
I0320 09:39:50.725533 40383 net.cpp:65] Memory required for Data0
I0320 09:39:50.725595 40383 net.cpp:76] Creating Layer data
I0320 09:39:50.725606 40383 net.cpp:112] data -> data
I0320 09:39:50.725621 40383 net.cpp:112] data -> label
I0320 09:39:50.725636 40383 video_data_layer.cpp:283] Opening file demo_list_test_uniform16_proposal.lst
I0320 09:39:50.726625 40383 video_data_layer.cpp:318] A total of 1589 video chunks.
I0320 09:39:50.726634 40383 video_data_layer.cpp:345] read video from frame/video_test_0000131/
F0320 09:39:50.726667 40383 video_data_layer.cpp:347] Check failed: ReadImageSequenceToVolumeDatum(file_list_[id].c_str(), 1, label_list_[id], new_length, new_height, new_width, sampling_rate, &datum) 
*** Check failure stack trace: ***
.....................................................................................................................................................................
could you give me some suggestion?Thank you very much.

**Comment by sophiazy** [comment]
Dear Mr shou:
I really appreciate for your suggestions.I have run the demo file successfully.Now I want to train my own dataset.I meet two question:
1)  I am not sure whether the training  and test dataset is the "annotation"  file involved video?
2)  the detect class is:
7 BaseballPitch
9 BasketballDunk
12 Billiards
21 CleanAndJerk
22 CliffDiving
23 CricketBowling
24 CricketShot
26 Diving
31 FrisbeeCatch
33 GolfSwing
36 HammerThrow
40 HighJump
45 JavelinThrow
51 LongJump
68 PoleVault
79 Shotput
85 SoccerPenalty
92 TennisSwing
93 ThrowDiscus
97 VolleyballSpiking

So when I create "list_train_uniform16_proposal.lst",the video label is within the above,for example,97.instead 0~20?

**Comment by Priyanka154** [comment]
/c3d_sport1m_feature_extraction_frm.sh: 7: ./c3d_sport1m_feature_extraction_frm.sh: ../../build/tools/extract_image_features.bin: not found

- 

- [ ]

**Comment by Priyanka154** [comment]
error occured when example is running 

v_BaseballPitch_g01_c01/000103.jpg
v_BaseballPitch_g01_c01/000104.jpg
v_BaseballPitch_g01_c01/000105.jpg
v_BaseballPitch_g01_c01/000106.jpg
v_BaseballPitch_g01_c01/000107.jpg
**_./c3d_sport1m_feature_extraction_frm.sh: 7: ./c3d_sport1m_feature_extraction_frm.sh: ../../build/tools/extract_image_features.bin: not found_**

**Comment by junaidwahid** [comment]
@Priyanka154  did you found the solution ?

**Comment by Priyanka154** [comment]
@junaidwahid  NOT YET,
IF YOU HAVE SOLUTION THN PLEASE GUIDE ME
