### ISSUE TITLE
question about "extract feature on my test dataset"

### ISSUE THREAD

**Issue by sophiazy** [zhengshou/scnn#6]
Hi Zheng,
I have some question about "extract feature on my test dataset"
in the "list_test_uniform16_proposal.lst",whether the label column need to be a ground truth or random setting?
in the "list_test_uniform16_localization.lst",whether the label and overlap column need to be a ground truth or random setting?
because when i run the demo ,I find the label and overlap column  are random settiing as all 0 in the "demo_list_test_uniform16_localization.lst" and "demo_list_test_uniform16_proposal.lst"
I would appreciated for some advice,very thanks!

**Comment by zhengshou** [comment]
No need to use ground truth. you can go for random settings.

**Comment by sophiazy** [comment]
Thank you for your help.

**Comment by sophiazy** [comment]
sorry to be a bothered again,I meet another question.
in the feature_extract.sh,How I set the multi-GPU?  use the"-gpu all" failed
.......................................................................................................................................................................................................................
GLOG_logtosterr=1 ../../../C3D_sample_rate/build/tools/extract_image_features.bin feature_extract.prototxt snapshot/SCNN_uniform16_binary_iter_30000 0 10 71094 list_test_prefix_proposal.lst prob 2>extract.log
.......................................................................................................................................................................................................................

**Comment by zhengshou** [comment]
I haven't tested it with multi-gpu

**Comment by sophiazy** [comment]
Hi zheng,
1) When I extract the feature for the segments using my own trained caffemodel,and use the" read_binary_blob " function to read the prob file,it is incredible that all prob return the same score.
2) But When I extract the feature for the segments using caffemodel that author provided in the file"scnn-master/models/THUMOS14/proposal/snapshot",different prob file return different score.and these score is reasonable
3) so I think my trained caffemodel is not correct.on the basis of your parameter setting ,I only change the dropout to 0.8  ,I hope for your advice ,very thanks!
the train_log is below:
.......................................................................................................................................................................................................................
I0330 21:52:41.880172 30499 solver.cpp:237] Iteration 29200, lr = 1e-06
I0330 21:52:41.880596 30499 solver.cpp:87] Iteration 29200, loss = 0.685713
I0330 21:52:42.266053 30499 softmax_loss_layer.cpp:41] softmax loss: 0.685817
I0330 21:52:42.670613 30499 softmax_loss_layer.cpp:41] softmax loss: 0.700536
I0330 21:52:43.021008 30499 softmax_loss_layer.cpp:41] softmax loss: 0.700439
I0330 21:52:43.288077 30499 softmax_loss_layer.cpp:41] softmax loss: 0.700249
I0330 21:52:43.647419 30499 softmax_loss_layer.cpp:41] softmax loss: 0.699978
I0330 21:52:44.073864 30499 softmax_loss_layer.cpp:41] softmax loss: 0.686704
I0330 21:52:44.401130 30499 softmax_loss_layer.cpp:41] softmax loss: 0.699421
I0330 21:52:44.718961 30499 softmax_loss_layer.cpp:41] softmax loss: 0.6872
I0330 21:52:45.085830 30499 softmax_loss_layer.cpp:41] softmax loss: 0.68736
I0330 21:52:45.501719 30499 softmax_loss_layer.cpp:41] softmax loss: 0.687405
I0330 21:52:45.792388 30499 softmax_loss_layer.cpp:41] softmax loss: 0.687347
I0330 21:52:46.148257 30499 softmax_loss_layer.cpp:41] softmax loss: 0.699134
I0330 21:52:46.529688 30499 softmax_loss_layer.cpp:41] softmax loss: 0.687159
I0330 21:52:46.942733 30499 softmax_loss_layer.cpp:41] softmax loss: 0.687028
I0330 21:52:47.186964 30499 softmax_loss_layer.cpp:41] softmax loss: 0.699523
I0330 21:52:47.557617 30499 softmax_loss_layer.cpp:41] softmax loss: 0.686716
I0330 21:52:47.956590 30499 softmax_loss_layer.cpp:41] softmax loss: 0.699806
I0330 21:52:48.328367 30499 softmax_loss_layer.cpp:41] softmax loss: 0.699873
I0330 21:52:48.596671 30499 softmax_loss_layer.cpp:41] softmax loss: 0.699832
I0330 21:53:30.802774 30499 softmax_loss_layer.cpp:41] softmax loss: 0.689091
I0330 21:53:31.020431 30499 softmax_loss_layer.cpp:41] softmax loss: 0.688819
I0330 21:53:31.252233 30499 softmax_loss_layer.cpp:41] softmax loss: 0.697842
I0330 21:53:31.488675 30499 softmax_loss_layer.cpp:41] softmax loss: 0.688265
I0330 21:53:31.706966 30499 softmax_loss_layer.cpp:41] softmax loss: 0.687978
I0330 21:53:31.935756 30499 softmax_loss_layer.cpp:41] softmax loss: 0.698705
I0330 21:53:32.166200 30499 softmax_loss_layer.cpp:41] softmax loss: 0.698929
I0330 21:53:32.402087 30499 softmax_loss_layer.cpp:41] softmax loss: 0.687299
I0330 21:53:32.624447 30499 softmax_loss_layer.cpp:41] softmax loss: 0.699221
I0330 21:53:32.841732 30499 softmax_loss_layer.cpp:41] softmax loss: 0.699291
I0330 21:53:33.067411 30499 softmax_loss_layer.cpp:41] softmax loss: 0.687078
I0330 21:53:33.297123 30499 softmax_loss_layer.cpp:41] softmax loss: 0.687013
I0330 21:53:33.297714 30499 solver.cpp:237] Iteration 29400, lr = 1e-06
I0330 21:53:33.298146 30499 solver.cpp:87] Iteration 29400, loss = 0.687013
I0330 21:53:33.531246 30499 softmax_loss_layer.cpp:41] softmax loss: 0.699479
I0330 21:53:33.750516 30499 softmax_loss_layer.cpp:41] softmax loss: 0.699521
I0330 21:53:33.968008 30499 softmax_loss_layer.cpp:41] softmax loss: 0.699458
I0330 21:53:34.201617 30499 softmax_loss_layer.cpp:41] softmax loss: 0.699299
I0330 21:53:34.430485 30499 softmax_loss_layer.cpp:41] softmax loss: 0.699056
I0330 21:53:34.663725 30499 softmax_loss_layer.cpp:41] softmax loss: 0.698735
I0330 21:53:34.880439 30499 softmax_loss_layer.cpp:41] softmax loss: 0.698346
I0330 21:53:35.094815 30499 softmax_loss_layer.cpp:41] softmax loss: 0.697895
I0330 21:53:35.328213 30499 softmax_loss_layer.cpp:41] softmax loss: 0.697388
I0330 21:53:35.566653 30499 softmax_loss_layer.cpp:41] softmax loss: 0.696831
I0330 21:53:35.795374 30499 softmax_loss_layer.cpp:41] softmax loss: 0.69623
I0330 21:53:36.013792 30499 softmax_loss_layer.cpp:41] softmax loss: 0.690712
I0330 21:53:36.250903 30499 softmax_loss_layer.cpp:41] softmax loss: 0.695111
I0330 21:53:36.559870 30499 softmax_loss_layer.cpp:41] softmax loss: 0.691715
I0330 21:53:36.776144 30499 softmax_loss_layer.cpp:41] softmax loss: 0.694205
I0330 21:53:37.004492 30499 softmax_loss_layer.cpp:41] softmax loss: 0.693766
I0330 21:53:37.228953 30499 softmax_loss_layer.cpp:41] softmax loss: 0.693023
I0330 21:53:37.464432 30499 softmax_loss_layer.cpp:41] softmax loss: 0.692926
I0330 21:53:37.684689 30499 softmax_loss_layer.cpp:41] softmax loss: 0.692516
I0330 21:53:37.909420 30499 softmax_loss_layer.cpp:41] softmax loss: 0.692047
I0330 21:53:37.909960 30499 solver.cpp:237] Iteration 29420, lr = 1e-06
I0330 21:53:37.910372 30499 solver.cpp:87] Iteration 29420, loss = 0.692047
I0330 21:53:38.136037 30499 softmax_loss_layer.cpp:41] softmax loss: 0.691525
I0330 21:53:38.367092 30499 softmax_loss_layer.cpp:41] softmax loss: 0.690956
I0330 21:53:38.590575 30499 softmax_loss_layer.cpp:41] softmax loss: 0.690344
I0330 21:53:38.812229 30499 softmax_loss_layer.cpp:41] softmax loss: 0.689695
I0330 21:53:39.035411 30499 softmax_loss_layer.cpp:41] softmax loss: 0.689012
I0330 21:53:39.263245 30499 softmax_loss_layer.cpp:41] softmax loss: 0.688298
I0330 21:53:39.502210 30499 softmax_loss_layer.cpp:41] softmax loss: 0.687558
I0330 21:53:39.724313 30499 softmax_loss_layer.cpp:41] softmax loss: 0.686793
I0330 21:53:39.945720 30499 softmax_loss_layer.cpp:41] softmax loss: 0.70034
I0330 21:53:40.179656 30499 softmax_loss_layer.cpp:41] softmax loss: 0.685398
I0330 21:53:40.415643 30499 softmax_loss_layer.cpp:41] softmax loss: 0.701612
I0330 21:53:40.635273 30499 softmax_loss_layer.cpp:41] softmax loss: 0.7021
I0330 21:53:40.853456 30499 softmax_loss_layer.cpp:41] softmax loss: 0.702438
I0330 21:53:41.075145 30499 softmax_loss_layer.cpp:41] softmax loss: 0.702641
I0330 21:53:41.304769 30499 softmax_loss_layer.cpp:41] softmax loss: 0.702721
I0330 21:53:41.540367 30499 softmax_loss_layer.cpp:41] softmax loss: 0.702691
I0330 21:53:41.763499 30499 softmax_loss_layer.cpp:41] softmax loss: 0.68382
I0330 21:53:41.990140 30499 softmax_loss_layer.cpp:41] softmax loss: 0.683835
I0330 21:53:42.213994 30499 softmax_loss_layer.cpp:41] softmax loss: 0.702633
I0330 21:53:42.447934 30499 softmax_loss_layer.cpp:41] softmax loss: 0.702608
I0330 21:53:42.448537 30499 solver.cpp:237] Iteration 29440, lr = 1e-06
I0330 21:53:42.448997 30499 solver.cpp:87] Iteration 29440, loss = 0.702608
I0330 21:53:42.674176 30499 softmax_loss_layer.cpp:41] softmax loss: 0.702484
I0330 21:53:42.889976 30499 softmax_loss_layer.cpp:41] softmax loss: 0.702271
I0330 21:53:43.112051 30499 softmax_loss_layer.cpp:41] softmax loss: 0.684395
I0330 21:53:43.334620 30499 softmax_loss_layer.cpp:41] softmax loss: 0.701812
I0330 21:53:43.571208 30499 softmax_loss_layer.cpp:41] softmax loss: 0.701562
I0330 21:53:43.794704 30499 softmax_loss_layer.cpp:41] softmax loss: 0.685123
I0330 21:53:44.030728 30499 softmax_loss_layer.cpp:41] softmax loss: 0.701043
I0330 21:53:44.305310 30499 softmax_loss_layer.cpp:41] softmax loss: 0.700767
I0330 21:53:44.534283 30499 softmax_loss_layer.cpp:41] softmax loss: 0.700417
I0330 21:53:44.779934 30499 softmax_loss_layer.cpp:41] softmax loss: 0.700001
I0330 21:53:45.004391 30499 softmax_loss_layer.cpp:41] softmax loss: 0.699525
I0330 21:53:45.242039 30499 softmax_loss_layer.cpp:41] softmax loss: 0.698996
I0330 21:53:45.474099 30499 softmax_loss_layer.cpp:41] softmax loss: 0.698419
I0330 21:53:45.690454 30499 softmax_loss_layer.cpp:41] softmax loss: 0.697799
I0330 21:53:45.919783 30499 softmax_loss_layer.cpp:41] softmax loss: 0.697141
I0330 21:53:46.143723 30499 softmax_loss_layer.cpp:41] softmax loss: 0.696448
I0330 21:53:46.380134 30499 softmax_loss_layer.cpp:41] softmax loss: 0.695724
I0330 21:53:46.635167 30499 softmax_loss_layer.cpp:41] softmax loss: 0.694972
I0330 21:53:46.861526 30499 softmax_loss_layer.cpp:41] softmax loss: 0.6921
I0330 21:53:47.089707 30499 softmax_loss_layer.cpp:41] softmax loss: 0.693598
I0330 21:53:47.090288 30499 solver.cpp:237] Iteration 29460, lr = 1e-06
I0330 21:53:47.090741 30499 solver.cpp:87] Iteration 29460, loss = 0.693598
I0330 21:53:47.323151 30499 softmax_loss_layer.cpp:41] softmax loss: 0.693335
I0330 21:53:47.543998 30499 softmax_loss_layer.cpp:41] softmax loss: 0.693809
I0330 21:53:47.775163 30499 softmax_loss_layer.cpp:41] softmax loss: 0.692159
I0330 21:53:48.009909 30499 softmax_loss_layer.cpp:41] softmax loss: 0.694531
I0330 21:53:48.243839 30499 softmax_loss_layer.cpp:41] softmax loss: 0.694785
I0330 21:53:48.466640 30499 softmax_loss_layer.cpp:41] softmax loss: 0.691383
I0330 21:53:48.681409 30499 softmax_loss_layer.cpp:41] softmax loss: 0.695131
I0330 21:53:48.912863 30499 softmax_loss_layer.cpp:41] softmax loss: 0.695225
I0330 21:53:49.147646 30499 softmax_loss_layer.cpp:41] softmax loss: 0.69109
I0330 21:53:49.374544 30499 softmax_loss_layer.cpp:41] softmax loss: 0.695295
I0330 21:53:49.596791 30499 softmax_loss_layer.cpp:41] softmax loss: 0.695272
I0330 21:53:49.826324 30499 softmax_loss_layer.cpp:41] softmax loss: 0.691148
I0330 21:53:50.059073 30499 softmax_loss_layer.cpp:41] softmax loss: 0.691157
I0330 21:53:50.293660 30499 softmax_loss_layer.cpp:41] softmax loss: 0.691066
I0330 21:53:50.511849 30499 softmax_loss_layer.cpp:41] softmax loss: 0.690884
I0330 21:53:50.734807 30499 softmax_loss_layer.cpp:41] softmax loss: 0.69062
I0330 21:53:50.970402 30499 softmax_loss_layer.cpp:41] softmax loss: 0.696018
I0330 21:53:51.211794 30499 softmax_loss_layer.cpp:41] softmax loss: 0.690082
I0330 21:53:51.430207 30499 softmax_loss_layer.cpp:41] softmax loss: 0.6898
I0330 21:53:51.658025 30499 softmax_loss_layer.cpp:41] softmax loss: 0.696861
I0330 21:53:51.658721 30499 solver.cpp:237] Iteration 29480, lr = 1e-06
I0330 21:53:51.659167 30499 solver.cpp:87] Iteration 29480, loss = 0.696861
I0330 21:53:51.883667 30499 softmax_loss_layer.cpp:41] softmax loss: 0.68923
I0330 21:53:52.112740 30499 softmax_loss_layer.cpp:41] softmax loss: 0.697377
I0330 21:53:52.346211 30499 softmax_loss_layer.cpp:41] softmax loss: 0.697544
I0330 21:53:52.567189 30499 softmax_loss_layer.cpp:41] softmax loss: 0.688721
I0330 21:53:52.793709 30499 softmax_loss_layer.cpp:41] softmax loss: 0.688578
I0330 21:53:53.020776 30499 softmax_loss_layer.cpp:41] softmax loss: 0.68835
I0330 21:53:53.257886 30499 softmax_loss_layer.cpp:41] softmax loss: 0.698274
I0330 21:53:53.480360 30499 softmax_loss_layer.cpp:41] softmax loss: 0.687873
I0330 21:53:53.696960 30499 softmax_loss_layer.cpp:41] softmax loss: 0.698707
I0330 21:53:53.930549 30499 softmax_loss_layer.cpp:41] softmax loss: 0.698838
I0330 21:53:54.161052 30499 softmax_loss_layer.cpp:41] softmax loss: 0.698855
I0330 21:53:54.423466 30499 softmax_loss_layer.cpp:41] softmax loss: 0.698768
I0330 21:53:54.794697 30499 softmax_loss_layer.cpp:41] softmax loss: 0.69859
I0330 21:53:55.215790 30499 softmax_loss_layer.cpp:41] softmax loss: 0.687993
I0330 21:53:55.542839 30499 softmax_loss_layer.cpp:41] softmax loss: 0.698193
I0330 21:53:55.855779 30499 softmax_loss_layer.cpp:41] softmax loss: 0.697969
I0330 21:53:56.160692 30499 softmax_loss_layer.cpp:41] softmax loss: 0.697668
I0330 21:53:56.532342 30499 softmax_loss_layer.cpp:41] softmax loss: 0.697296
I0330 21:53:56.786099 30499 softmax_loss_layer.cpp:41] softmax loss: 0.69686
I0330 21:53:57.128010 30499 softmax_loss_layer.cpp:41] softmax loss: 0.696367
I0330 21:53:57.128649 30499 solver.cpp:237] Iteration 29500, lr = 1e-06
I0330 21:53:57.129098 30499 solver.cpp:87] Iteration 29500, loss = 0.696367
I0330 21:53:57.448796 30499 softmax_loss_layer.cpp:41] softmax loss: 0.695824
I0330 21:54:58.192781 30499 solver.cpp:87] Iteration 29720, loss = 0.693876
I0330 21:54:58.416596 30499 softmax_loss_layer.cpp:41] softmax loss: 0.693413
I0330 21:54:58.641474 30499 softmax_loss_layer.cpp:41] softmax loss: 0.693398
I0330 21:54:58.871644 30499 softmax_loss_layer.cpp:41] softmax loss: 0.693764
I0330 21:54:59.108295 30499 softmax_loss_layer.cpp:41] softmax loss: 0.693993
I0330 21:54:59.326488 30499 softmax_loss_layer.cpp:41] softmax loss: 0.694098
I0330 21:54:59.676996 30499 softmax_loss_layer.cpp:41] softmax loss: 0.694093
I0330 21:54:59.943511 30499 softmax_loss_layer.cpp:41] softmax loss: 0.692307
I0330 21:55:00.292217 30499 softmax_loss_layer.cpp:41] softmax loss: 0.693994
I0330 21:55:00.620148 30499 softmax_loss_layer.cpp:41] softmax loss: 0.692396
I0330 21:55:00.906908 30499 softmax_loss_layer.cpp:41] softmax loss: 0.693914
I0330 21:55:01.263695 30499 softmax_loss_layer.cpp:41] softmax loss: 0.692468
I0330 21:55:01.523694 30499 softmax_loss_layer.cpp:41] softmax loss: 0.692446
I0330 21:55:01.869478 30499 softmax_loss_layer.cpp:41] softmax loss: 0.693968
I0330 21:55:02.194624 30499 softmax_loss_layer.cpp:41] softmax loss: 0.69232
I0330 21:55:02.486351 30499 softmax_loss_layer.cpp:41] softmax loss: 0.694082
I0330 21:55:02.851871 30499 softmax_loss_layer.cpp:41] softmax loss: 0.692217
I0330 21:55:03.111887 30499 softmax_loss_layer.cpp:41] softmax loss: 0.692121
I0330 21:55:03.460393 30499 softmax_loss_layer.cpp:41] softmax loss: 0.694361
I0330 21:55:03.800711 30499 softmax_loss_layer.cpp:41] softmax loss: 0.694428
I0330 21:55:04.073810 30499 softmax_loss_layer.cpp:41] softmax loss: 0.694389
I0330 21:55:04.074489 30499 solver.cpp:237] Iteration 29740, lr = 1e-06
I0330 21:55:04.074944 30499 solver.cpp:87] Iteration 29740, loss = 0.694389
I0330 21:55:04.439141 30499 softmax_loss_layer.cpp:41] softmax loss: 0.692042
I0330 21:55:04.707347 30499 softmax_loss_layer.cpp:41] softmax loss: 0.694232
I0330 21:55:05.051339 30499 softmax_loss_layer.cpp:41] softmax loss: 0.694112
I0330 21:55:05.389072 30499 softmax_loss_layer.cpp:41] softmax loss: 0.692392
I0330 21:55:05.663599 30499 softmax_loss_layer.cpp:41] softmax loss: 0.693816
I0330 21:55:06.028690 30499 softmax_loss_layer.cpp:41] softmax loss: 0.693637
I0330 21:55:06.282744 30499 softmax_loss_layer.cpp:41] softmax loss: 0.693376
I0330 21:55:06.632028 30499 softmax_loss_layer.cpp:41] softmax loss: 0.693041
I0330 21:55:06.964565 30499 softmax_loss_layer.cpp:41] softmax loss: 0.69264
I0330 21:55:07.247856 30499 softmax_loss_layer.cpp:41] softmax loss: 0.694116
I0330 21:55:07.616181 30499 softmax_loss_layer.cpp:41] softmax loss: 0.691865
I0330 21:55:07.987996 30499 softmax_loss_layer.cpp:41] softmax loss: 0.691482
I0330 21:55:08.243178 30499 softmax_loss_layer.cpp:41] softmax loss: 0.691038
I0330 21:55:08.607975 30499 softmax_loss_layer.cpp:41] softmax loss: 0.695762
I0330 21:55:08.892848 30499 softmax_loss_layer.cpp:41] softmax loss: 0.690191
I0330 21:55:09.215472 30499 softmax_loss_layer.cpp:41] softmax loss: 0.689777
I0330 21:55:09.576577 30499 softmax_loss_layer.cpp:41] softmax loss: 0.697003
I0330 21:55:09.835434 30499 softmax_loss_layer.cpp:41] softmax loss: 0.697329
I0330 21:55:10.200932 30499 softmax_loss_layer.cpp:41] softmax loss: 0.688791
I0330 21:55:10.490118 30499 softmax_loss_layer.cpp:41] softmax loss: 0.697796
I0330 21:55:10.490721 30499 solver.cpp:237] Iteration 29760, lr = 1e-06
I0330 21:55:10.491152 30499 solver.cpp:87] Iteration 29760, loss = 0.697796
I0330 21:55:10.805599 30499 softmax_loss_layer.cpp:41] softmax loss: 0.688376
I0330 21:55:11.167071 30499 softmax_loss_layer.cpp:41] softmax loss: 0.698172
I0330 21:55:11.429600 30499 softmax_loss_layer.cpp:41] softmax loss: 0.698279
I0330 21:55:11.792820 30499 softmax_loss_layer.cpp:41] softmax loss: 0.688046
I0330 21:55:12.087077 30499 softmax_loss_layer.cpp:41] softmax loss: 0.69837
I0330 21:55:12.403861 30499 softmax_loss_layer.cpp:41] softmax loss: 0.687966
I0330 21:55:12.783079 30499 softmax_loss_layer.cpp:41] softmax loss: 0.698442
I0330 21:55:13.031661 30499 softmax_loss_layer.cpp:41] softmax loss: 0.698419
I0330 21:55:13.387714 30499 softmax_loss_layer.cpp:41] softmax loss: 0.688024
I0330 21:55:13.682626 30499 softmax_loss_layer.cpp:41] softmax loss: 0.698287
I0330 21:55:13.987406 30499 softmax_loss_layer.cpp:41] softmax loss: 0.688142
I0330 21:55:14.371126 30499 softmax_loss_layer.cpp:41] softmax loss: 0.698178
I0330 21:55:14.633061 30499 softmax_loss_layer.cpp:41] softmax loss: 0.68824
I0330 21:55:14.979718 30499 softmax_loss_layer.cpp:41] softmax loss: 0.698089
I0330 21:55:15.295940 30499 softmax_loss_layer.cpp:41] softmax loss: 0.697997
I0330 21:55:15.601809 30499 softmax_loss_layer.cpp:41] softmax loss: 0.697813
I0330 21:55:15.991101 30499 softmax_loss_layer.cpp:41] softmax loss: 0.697547
I0330 21:55:16.247521 30499 softmax_loss_layer.cpp:41] softmax loss: 0.697207
I0330 21:55:16.587347 30499 softmax_loss_layer.cpp:41] softmax loss: 0.6968
I0330 21:55:16.900326 30499 softmax_loss_layer.cpp:41] softmax loss: 0.696333
I0330 21:55:16.901099 30499 solver.cpp:237] Iteration 29780, lr = 1e-06
I0330 21:55:16.901546 30499 solver.cpp:87] Iteration 29780, loss = 0.696333
I0330 21:55:17.193739 30499 softmax_loss_layer.cpp:41] softmax loss: 0.695812
I0330 21:55:17.574575 30499 softmax_loss_layer.cpp:41] softmax loss: 0.695243
I0330 21:55:17.833178 30499 softmax_loss_layer.cpp:41] softmax loss: 0.691665
I0330 21:55:18.172250 30499 softmax_loss_layer.cpp:41] softmax loss: 0.694181
I0330 21:55:18.478534 30499 softmax_loss_layer.cpp:41] softmax loss: 0.692619
I0330 21:55:18.781782 30499 softmax_loss_layer.cpp:41] softmax loss: 0.693321
I0330 21:55:19.149214 30499 softmax_loss_layer.cpp:41] softmax loss: 0.692902
I0330 21:55:19.421434 30499 softmax_loss_layer.cpp:41] softmax loss: 0.692425
I0330 21:55:19.767470 30499 softmax_loss_layer.cpp:41] softmax loss: 0.6944
I0330 21:55:20.061605 30499 softmax_loss_layer.cpp:41] softmax loss: 0.69152
I0330 21:55:20.359414 30499 softmax_loss_layer.cpp:41] softmax loss: 0.691082
I0330 21:55:20.713975 30499 softmax_loss_layer.cpp:41] softmax loss: 0.695712
I0330 21:55:20.986169 30499 softmax_loss_layer.cpp:41] softmax loss: 0.690245
I0330 21:55:21.342453 30499 softmax_loss_layer.cpp:41] softmax loss: 0.689836
I0330 21:55:21.641824 30499 softmax_loss_layer.cpp:41] softmax loss: 0.689369
I0330 21:55:21.942441 30499 softmax_loss_layer.cpp:41] softmax loss: 0.68885
I0330 21:55:22.312680 30499 softmax_loss_layer.cpp:41] softmax loss: 0.688284
I0330 21:55:22.583408 30499 softmax_loss_layer.cpp:41] softmax loss: 0.687675
I0330 21:55:22.932082 30499 softmax_loss_layer.cpp:41] softmax loss: 0.699303
I0330 21:55:23.239511 30499 softmax_loss_layer.cpp:41] softmax loss: 0.69979
I0330 21:55:23.240145 30499 solver.cpp:237] Iteration 29800, lr = 1e-06
I0330 21:55:23.240577 30499 solver.cpp:87] Iteration 29800, loss = 0.69979
I0330 21:55:23.537458 30499 softmax_loss_layer.cpp:41] softmax loss: 0.700127
I0330 21:55:23.920137 30499 softmax_loss_layer.cpp:41] softmax loss: 0.70033
I0330 21:55:24.195349 30499 softmax_loss_layer.cpp:41] softmax loss: 0.685936
I0330 21:55:24.530474 30499 softmax_loss_layer.cpp:41] softmax loss: 0.685766
I0330 21:55:24.843049 30499 softmax_loss_layer.cpp:41] softmax loss: 0.700838
I0330 21:55:25.130220 30499 softmax_loss_layer.cpp:41] softmax loss: 0.685388
I0330 21:55:25.504806 30499 softmax_loss_layer.cpp:41] softmax loss: 0.685176
I0330 21:55:25.773638 30499 softmax_loss_layer.cpp:41] softmax loss: 0.701476
I0330 21:55:26.116024 30499 softmax_loss_layer.cpp:41] softmax loss: 0.684726
I0330 21:55:26.435428 30499 softmax_loss_layer.cpp:41] softmax loss: 0.684484
I0330 21:55:26.721515 30499 softmax_loss_layer.cpp:41] softmax loss: 0.702208
I0330 21:55:27.093068 30499 softmax_loss_layer.cpp:41] softmax loss: 0.683983
I0330 21:55:27.365892 30499 softmax_loss_layer.cpp:41] softmax loss: 0.683718
I0330 21:55:27.702255 30499 softmax_loss_layer.cpp:41] softmax loss: 0.703008
I0330 21:55:28.014513 30499 softmax_loss_layer.cpp:41] softmax loss: 0.703215
I0330 21:55:28.308182 30499 softmax_loss_layer.cpp:41] softmax loss: 0.703299
I0330 21:55:28.689635 30499 softmax_loss_layer.cpp:41] softmax loss: 0.703272
I0330 21:55:28.969141 30499 softmax_loss_layer.cpp:41] softmax loss: 0.703146
I0330 21:55:29.304603 30499 softmax_loss_layer.cpp:41] softmax loss: 0.702931
I0330 21:55:29.621608 30499 softmax_loss_layer.cpp:41] softmax loss: 0.702635
I0330 21:55:29.622242 30499 solver.cpp:237] Iteration 29820, lr = 1e-06
I0330 21:55:29.622684 30499 solver.cpp:87] Iteration 29820, loss = 0.702635
I0330 21:55:29.901154 30499 softmax_loss_layer.cpp:41] softmax loss: 0.702267
I0330 21:55:30.276088 30499 softmax_loss_layer.cpp:41] softmax loss: 0.684535
I0330 21:55:30.551174 30499 softmax_loss_layer.cpp:41] softmax loss: 0.701545
I0330 21:55:30.898223 30499 softmax_loss_layer.cpp:41] softmax loss: 0.685176
I0330 21:55:31.217505 30499 softmax_loss_layer.cpp:41] softmax loss: 0.700957
I0330 21:55:31.484302 30499 softmax_loss_layer.cpp:41] softmax loss: 0.685698
I0330 21:55:31.859210 30499 softmax_loss_layer.cpp:41] softmax loss: 0.68587
I0330 21:55:32.135751 30499 softmax_loss_layer.cpp:41] softmax loss: 0.700421
I0330 21:55:32.476821 30499 softmax_loss_layer.cpp:41] softmax loss: 0.686076
I0330 21:55:32.792306 30499 softmax_loss_layer.cpp:41] softmax loss: 0.700231
I0330 21:55:33.070559 30499 softmax_loss_layer.cpp:41] softmax loss: 0.700097
I0330 21:55:33.445618 30499 softmax_loss_layer.cpp:41] softmax loss: 0.699874
I0330 21:55:33.715031 30499 softmax_loss_layer.cpp:41] softmax loss: 0.699572
I0330 21:55:34.071743 30499 softmax_loss_layer.cpp:41] softmax loss: 0.699199
I0330 21:56:30.661684 30499 net.cpp:291] Copying source layer data
I0330 21:56:30.661694 30499 net.cpp:291] Copying source layer conv1a
I0330 21:56:30.661701 30499 net.cpp:291] Copying source layer relu1a
I0330 21:56:30.661706 30499 net.cpp:291] Copying source layer pool1
I0330 21:56:30.661711 30499 net.cpp:291] Copying source layer conv2a
I0330 21:56:30.661718 30499 net.cpp:291] Copying source layer relu2a
I0330 21:56:30.661723 30499 net.cpp:291] Copying source layer pool2
I0330 21:56:30.661728 30499 net.cpp:291] Copying source layer conv3a
I0330 21:56:30.661734 30499 net.cpp:291] Copying source layer relu3a
I0330 21:56:30.661751 30499 net.cpp:291] Copying source layer conv3b
I0330 21:56:30.661759 30499 net.cpp:291] Copying source layer relu3b
I0330 21:56:30.661765 30499 net.cpp:291] Copying source layer pool3
I0330 21:56:30.661772 30499 net.cpp:291] Copying source layer conv4a
I0330 21:56:30.661787 30499 net.cpp:291] Copying source layer relu4a
I0330 21:56:30.661793 30499 net.cpp:291] Copying source layer conv4b
I0330 21:56:30.661799 30499 net.cpp:291] Copying source layer relu4b
I0330 21:56:30.661805 30499 net.cpp:291] Copying source layer pool4
I0330 21:56:30.661810 30499 net.cpp:291] Copying source layer conv5a
I0330 21:56:30.661818 30499 net.cpp:291] Copying source layer relu5a
I0330 21:56:30.661825 30499 net.cpp:291] Copying source layer conv5b
I0330 21:56:30.661831 30499 net.cpp:291] Copying source layer relu5b
I0330 21:56:30.661837 30499 net.cpp:291] Copying source layer pool5
I0330 21:56:30.661842 30499 net.cpp:291] Copying source layer fc6-1
I0330 21:56:30.661849 30499 net.cpp:291] Copying source layer relu6
I0330 21:56:30.661855 30499 net.cpp:291] Copying source layer drop6
I0330 21:56:30.661862 30499 net.cpp:291] Copying source layer fc7-1
I0330 21:56:30.661870 30499 net.cpp:291] Copying source layer relu7
I0330 21:56:30.661876 30499 net.cpp:291] Copying source layer drop7
I0330 21:56:30.661882 30499 net.cpp:291] Copying source layer fc8
I0330 21:56:30.661890 30499 net.cpp:288] Ignoring source layer loss
I0330 22:19:42.047435 30499 solver.cpp:142] Test score #0: 0.0520392
I0330 22:19:42.047492 30499 solver.cpp:142] Test score #1: 0.716958
I0330 22:19:42.047508 30499 net.cpp:355] Serializing 30 layers
I0330 22:19:43.462921 30499 solver.cpp:159] Snapshotting to snapshot/SCNN_uniform16_binary_iter_30000
I0330 22:19:47.632897 30499 solver.cpp:166] Snapshotting solver state to snapshot/SCNN_uniform16_binary_iter_30000.solverstate
I0330 22:19:51.061259 30499 net.cpp:355] Serializing 30 layers
I0330 22:19:53.093744 30499 solver.cpp:159] Snapshotting to snapshot/SCNN_uniform16_binary_iter_30000
I0330 22:19:58.016034 30499 solver.cpp:166] Snapshotting solver state to snapshot/SCNN_uniform16_binary_iter_30000.solverstate
I0330 22:20:01.018657 30499 solver.cpp:100] Optimization Done.
I0330 22:20:01.018709 30499 finetune_net.cpp:30] Optimization Done.
