### ISSUE TITLE
finetune_proposal network

### ISSUE THREAD

**Issue by Kerry0123** [zhengshou/scnn#7]
Hi,
I have some questions about finetuning  S-CNN (proposal network).
list_train_uniform16_proposal.lst:
1./dataset/THUMOS14/val/validation_frm_all/video_validation_0000051/ 2561 1 8
2./dataset/THUMOS14/val/validation_frm_all/video_validation_0000051/ 2593 1 8
3./dataset/THUMOS14/val/validation_frm_all/video_validation_0000051/ 1985 1 16
4./dataset/THUMOS14/val/validation_frm_all/video_validation_0000051/ 2049 1 16
/dataset/THUMOS14/val/validation_frm_all/video_validation_0000051/ 4161 1 16
/dataset/THUMOS14/val/validation_frm_all/video_validation_0000051/ 4225 1 16
1.2561  is the index of the action start frame , 1 is postive label ,8 is stepsize. 2593-2561=32,why stepsize=8?
2.example：2561 is the index of the action start frame,stepsize is 16 up to 512，computing IOU with ground truth → label  is postive or background ?
/dataset/THUMOS14/val/validation_frm_all/video_validation_0000051/ 2561 1 16
/dataset/THUMOS14/val/validation_frm_all/video_validation_0000051/ 2561 1 32
/dataset/THUMOS14/val/validation_frm_all/video_validation_0000051/ 2561 1 64
/dataset/THUMOS14/val/validation_frm_all/video_validation_0000051/ 2561 1 128
/dataset/THUMOS14/val/validation_frm_all/video_validation_0000051/ 2561 1 256
/dataset/THUMOS14/val/validation_frm_all/video_validation_0000051/ 2561 1 512

 Is my understanding correct?
Thanks very much.

**Comment by Kerry0123** [comment]
I thought about it again.sample one segment by 8 or 16 stepsize ,right? 
example： 2561 2569 2577 ... (compose 16 frames →one segment) 
I can set stepsize to 1 or 2 about the short videos.right?

**Comment by zhengshou** [comment]
Yes you are right

**Comment by Kerry0123** [comment]
thanks.(端午节快乐)
