### ISSUE TITLE
Detailed instructions on running demo

### ISSUE THREAD

**Issue by kousik97** [zhengshou/scnn#8]
I want to run the demo using python. Should I also have matlab installed?
Can you also mention the detailed steps to run the demo in CPU
Can you please highlight on how to compile C3D_overlap_loss and C3D_sample_rate.

**Comment by zhengshou** [comment]
No matlab is needed to run the python code.

**Comment by kousik97** [comment]
Thank you so much for your response, can you also mention how to run the demo in CPU mode.
