### ISSUE TITLE
Compile error while trying to compile C3D_overlap_loss

### ISSUE THREAD

**Issue by kousik97** [zhengshou/scnn#9]
I get the following error while trying to run make all in C3D_overlap_loss:
I am using CPU and changed the Makefile.config accordingly
Also, I have already compiled c3d .

In file included from src/caffe/net.cpp:8:0:
./include/caffe/common.hpp:107:17: error: 'cublasHandle_t' does not name a type
   inline static cublasHandle_t cublas_handle() { return Get().cublas_handle_; }
                 ^
./include/caffe/common.hpp:108:17: error: 'curandGenerator_t' does not name a type
   inline static curandGenerator_t curand_generator() {
                 ^
./include/caffe/common.hpp:133:3: error: 'cublasHandle_t' does not name a type
   cublasHandle_t cublas_handle_;
   ^
./include/caffe/common.hpp:134:3: error: 'curandGenerator_t' does not name a type
   curandGenerator_t curand_generator_;
   ^
./include/caffe/common.hpp:149:34: error: 'cublasStatus_t' was not declared in this scope
 const char* cublasGetErrorString(cublasStatus_t error);
                                  ^
./include/caffe/common.hpp:150:34: error: 'curandStatus_t' was not declared in this scope
 const char* curandGetErrorString(curandStatus_t error);
                                  ^
make: *** [build/src/caffe/net.o] Error 1

**Comment by zhengshou** [comment]
Please refer to C3D for details about compilation
